# Generated by Django 4.1.7 on 2023-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplierUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierID', models.CharField(max_length=50)),
                ('SCAC', models.CharField(max_length=50)),
                ('DUNS', models.CharField(max_length=50)),
                ('emailAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='suppResp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppAzureId', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
