# Generated by Django 4.1.7 on 2023-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supmgn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieruser',
            name='DUNS',
        ),
        migrations.RemoveField(
            model_name='supplieruser',
            name='SCAC',
        ),
        migrations.RemoveField(
            model_name='supplieruser',
            name='supplierID',
        ),
        migrations.AddField(
            model_name='suppresp',
            name='errorMessage',
            field=models.CharField(default='TextError', max_length=2000),
        ),
    ]
